COL_JOB_KEY = "Job_Key"
COL_TASK_KEY = "Task_Key"
COL_MONTH_KEY = "Month_Key"
COL_HOURS = "Hours"
COL_COST = "Cost"
COL_ALLOCATED_REVENUE = "Allocated_Revenue"
COL_AMOUNT = "Amount"
COL_JOB_MONTH_TOTAL_HOURS = "Job_Month_Total_Hours"
COL_SOURCE = "Source"
COL_QUOTED_TIME = "[Job Task] Quoted Time"
COL_QUOTED_AMOUNT = "[Job Task] Quoted Amount"
COL_BASE_RATE = "[Task] Base Rate"
COL_BILLABLE_RATE = "[Task] Billable Rate"
COL_BASE_RATE_QUOTE = "[Task] Base Rate_QUOTE"
COL_BILLABLE_RATE_QUOTE = "[Task] Billable Rate_QUOTE"

ROW_TASK_MONTH = "TASK_MONTH"
ROW_UNALLOCATED = "UNALLOCATED_REV"
ROW_QUOTE_ONLY = "QUOTE_ONLY"

REQUIRED_COLUMNS = [
    COL_JOB_KEY,
    COL_TASK_KEY,
    COL_MONTH_KEY,
    COL_HOURS,
    COL_COST,
    COL_ALLOCATED_REVENUE,
    COL_AMOUNT,
    COL_JOB_MONTH_TOTAL_HOURS,
    COL_SOURCE,
    COL_QUOTED_TIME,
    COL_QUOTED_AMOUNT,
    COL_BASE_RATE,
    COL_BILLABLE_RATE,
    COL_BASE_RATE_QUOTE,
    COL_BILLABLE_RATE_QUOTE,
]
